file-system:
  image: file-system
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database
    # - MONGODB_PORT
    # - MONGODB_DATABASE=USE_HASKELL_DB
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command: /usr/local/bin/file-system-exe
  ports:
    - "8080:8080"
  links:
    - database
database:
  image: mongo:3.2.11
  ports:
    - "27017:27017"
