fileserver-service:
  image: fileserver-service
  environment:
    - MONGODB_IP=docstore
    - POSTGRESQL_IP=authstore

  command: /usr/local/bin/fileserver-service-exe
  ports:
    - "8080:8080"
  links:
    - docstore

docstore:
  image: mongo:3.2.11
  ports:
    - "27017:27017"

authstore:
  restart: always
  image: postgres:9.6.1
  ports:
    - "5433:5432"
  environment:
    POSTGRES_USER: docker

registry:
  image: redis
  ports:
  - "6379:6379"
